name: Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-16.04
    env:
      working-directory: ./build/src 
    name: Unit Tests
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: yarn install
        run: yarn install
        working-directory: ${{ env.working-directory }}
      - name: yarn lint
        run: yarn lint
        working-directory: ${{ env.working-directory }}
      - name: yarn test
        run: yarn test
        working-directory: ${{ env.working-directory }}
