name: Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./build/src   
    steps:
      - uses: actions/checkout@v2
      - name: In app tests 
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - working-directory: ${{ env.working-directory }}     
      - run: yarn install
      - run: yarn lint
      - run: yarn test
