name: Release
on: 
  push:
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TRAVIS: yes
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: dappnodesdk install
        run: npm install -g @dappnode/dappnodesdk
      - name: Docker-Compose Build
        run: docker-compose build
      - name: publish
        run: dappnodesdk publish patch --dappnode_team_preset --provider infura

